Twitter/Twitter/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Twitter.Models;

namespace Twitter.Controllers
{
    [Authorize]
    public class PostController : Controller
    {
        TwitterDBContext TwitterDB = new TwitterDBContext();

        [HttpGet]
        public ActionResult New()
        {
            return View();
        }

        [HttpPost]
        public ActionResult New(Post post)
        {
            TwitterDB.Posts.Attach(post);
            TwitterDB.Posts.Add(post);
            TwitterDB.Users.Find(Membership.GetUser().ProviderUserKey.ToString()).Posts.Add(TwitterDB.Posts.Find(post.Id));
            TwitterDB.SaveChanges();
            return RedirectToAction("StartPage", "Twitter");
        }

        [HttpGet]
        public ActionResult Delete(int ID)
        {
            return View(TwitterDB.Posts.Find(ID));
        }
        [HttpPost]
        public ActionResult Delete(Post post)
        {
            TwitterDB.Posts.Attach(post);
            TwitterDB.Posts.Remove(post);
            TwitterDB.Users.Find(Membership.GetUser().ProviderUserKey.ToString()).Posts.Remove(TwitterDB.Posts.Find(post.Id));
            TwitterDB.SaveChanges();

            return RedirectToAction("StartPage", "Twitter");
        }

        [HttpGet]
        public ActionResult Edit(int ID)
        {
            return View(TwitterDB.Posts.Find(ID));
        }
        [HttpPost]
        public ActionResult Edit(Post post)
        {
            TwitterDB.Posts.Remove(TwitterDB.Posts.Find(post.Id));
            TwitterDB.Posts.Add(post);
            TwitterDB.SaveChanges();
            return RedirectToAction("StartPage", "Twitter");
        }

        public ActionResult Details(int ID)
        {
            return View(TwitterDB.Posts.Find(ID));
        }
    }
}

Twitter/Twitter/Views/Shared/Follow.cshtml
<div class="follow" data-id="@Model">Follow this user!</div>

Twitter/Twitter/Views/Shared/PostDetails.cshtml
@model Twitter.Models.Post

<div class="container col-lg-5 col-md-5 post">
    <h4>
        Published by: @Html.DisplayFor(model => model.Publisher.UserName)
    </h4>
    <p>
        @Html.DisplayFor(model => model.Title)
        <br />
        @Html.DisplayFor(model => model.Body)
    </p>
    <br />
    <p>
        Published on: @Html.DisplayFor(model => model.PublishedOn)
    </p>
    @Html.Partial("Unfollow", Model.Publisher.Id)
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Delete", "Delete", new { id = Model.Id })
</div>

Twitter/Twitter/Views/Shared/PostInput.cshtml
@model Twitter.Models.Post

<div class="form-horizontal">
    <h4>Create your post!</h4>
    <hr />
    <h2>@Html.EditorFor(model => model.Title)</h2>
    <p>@Html.EditorFor(model => model.Body)</p>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="@((Model == null)? "Create":"Save")" class="btn btn-default" />
        </div>
    </div>
</div>

Twitter/Twitter/Views/Shared/Unfollow.cshtml
<div class="unfollow" data-id="@Model">Unfollow this user!</div>

Twitter/Twitter/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My Twitter Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Twitter", "StartPage", "Twitter", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Create a new post", "Create", "Post", new { area = "" }, new { @class = "navbar-item" })</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My Twitter Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>